package pokdeng;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class PokDeng extends javax.swing.JFrame {

    Game g = new Game();

    /**
     * Creates new form JFrame
     */
    public PokDeng() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        gamePanel = new java.awt.Panel();
        cardLabel1 = new javax.swing.JLabel();
        cardPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cardPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pointsLabel1 = new javax.swing.JLabel();
        gameLabel1 = new javax.swing.JLabel();
        gameLabel2 = new javax.swing.JLabel();
        cardLabel2 = new javax.swing.JLabel();
        cardPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cardPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cardPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pointsLabel2 = new javax.swing.JLabel();
        pointsLabel3 = new javax.swing.JLabel();
        pointsLabel4 = new javax.swing.JLabel();
        pokdengLabel1 = new javax.swing.JLabel();
        pokdengLabel2 = new javax.swing.JLabel();
        menuPanel = new java.awt.Panel();
        newGameButton = new javax.swing.JButton();
        changeBetButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        stayButton = new javax.swing.JButton();
        currentFundLabel = new javax.swing.JLabel();
        betLabel = new javax.swing.JLabel();
        betLabel2 = new javax.swing.JLabel();
        fundLabel2 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pok Deng Game");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);

        gamePanel.setBackground(new java.awt.Color(0, 51, 0));
        gamePanel.setForeground(new java.awt.Color(255, 255, 255));

        cardLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cardLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cardLabel1.setText("Your Cards :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAB");

        javax.swing.GroupLayout cardPanel1Layout = new javax.swing.GroupLayout(cardPanel1);
        cardPanel1.setLayout(cardPanel1Layout);
        cardPanel1Layout.setHorizontalGroup(
                cardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cardPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardPanel1Layout.setVerticalGroup(
                cardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanel1Layout.createSequentialGroup()
                                .addContainerGap(59, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(59, 59, 59))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAB");

        javax.swing.GroupLayout cardPanel2Layout = new javax.swing.GroupLayout(cardPanel2);
        cardPanel2.setLayout(cardPanel2Layout);
        cardPanel2Layout.setHorizontalGroup(
                cardPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cardPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardPanel2Layout.setVerticalGroup(
                cardPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanel2Layout.createSequentialGroup()
                                .addContainerGap(59, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAB");

        javax.swing.GroupLayout cardPanel3Layout = new javax.swing.GroupLayout(cardPanel3);
        cardPanel3.setLayout(cardPanel3Layout);
        cardPanel3Layout.setHorizontalGroup(
                cardPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cardPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardPanel3Layout.setVerticalGroup(
                cardPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanel3Layout.createSequentialGroup()
                                .addContainerGap(59, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59))
        );

        pointsLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel1.setText("Your Points :");

        gameLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        gameLabel1.setForeground(new java.awt.Color(240, 240, 240));
        gameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameLabel1.setText("WELCOME");

        gameLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gameLabel2.setForeground(new java.awt.Color(240, 240, 240));
        gameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameLabel2.setText("Press New Game to start!");

        cardLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cardLabel2.setForeground(new java.awt.Color(255, 255, 255));
        cardLabel2.setText("Dealer Cards :");

        cardPanel5.setPreferredSize(new java.awt.Dimension(100, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LAB");

        javax.swing.GroupLayout cardPanel5Layout = new javax.swing.GroupLayout(cardPanel5);
        cardPanel5.setLayout(cardPanel5Layout);
        cardPanel5Layout.setHorizontalGroup(
                cardPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cardPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardPanel5Layout.setVerticalGroup(
                cardPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanel5Layout.createSequentialGroup()
                                .addContainerGap(59, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59))
        );

        cardPanel4.setPreferredSize(new java.awt.Dimension(100, 140));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LAB");

        javax.swing.GroupLayout cardPanel4Layout = new javax.swing.GroupLayout(cardPanel4);
        cardPanel4.setLayout(cardPanel4Layout);
        cardPanel4Layout.setHorizontalGroup(
                cardPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cardPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardPanel4Layout.setVerticalGroup(
                cardPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanel4Layout.createSequentialGroup()
                                .addContainerGap(59, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59))
        );

        cardPanel6.setPreferredSize(new java.awt.Dimension(100, 140));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LAB");

        javax.swing.GroupLayout cardPanel6Layout = new javax.swing.GroupLayout(cardPanel6);
        cardPanel6.setLayout(cardPanel6Layout);
        cardPanel6Layout.setHorizontalGroup(
                cardPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cardPanel6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardPanel6Layout.setVerticalGroup(
                cardPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanel6Layout.createSequentialGroup()
                                .addContainerGap(59, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(59, 59, 59))
        );

        pointsLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLabel2.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel2.setText("Dealer Points :");

        pointsLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLabel3.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointsLabel3.setText("0");

        pointsLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLabel4.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointsLabel4.setText("0");

        pokdengLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pokdengLabel1.setForeground(new java.awt.Color(240, 240, 240));
        pokdengLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokdengLabel1.setText("PokDeng");

        pokdengLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pokdengLabel2.setForeground(new java.awt.Color(240, 240, 240));
        pokdengLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokdengLabel2.setText("PokDeng");

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
                gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gamePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                .addComponent(cardLabel1)
                                                                .addGap(22, 22, 22)
                                                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                                .addComponent(cardPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(cardPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(cardPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(pointsLabel1))
                                                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                                                .addGap(41, 41, 41)
                                                                                                .addComponent(pointsLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                        .addComponent(pokdengLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                .addComponent(cardLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cardPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cardPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cardPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(pointsLabel2))
                                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                                .addGap(41, 41, 41)
                                                                                .addComponent(pointsLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(pokdengLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(gameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(156, 156, 156))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
        );
        gamePanelLayout.setVerticalGroup(
                gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cardLabel2)
                                        .addComponent(cardPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cardPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cardPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                .addComponent(pointsLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pointsLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pokdengLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(gameLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gameLabel2)
                                .addGap(39, 39, 39)
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(gamePanelLayout.createSequentialGroup()
                                                .addComponent(pointsLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pointsLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pokdengLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cardLabel1)
                                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cardPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cardPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cardPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        menuPanel.setBackground(new java.awt.Color(204, 255, 204));

        newGameButton.setText("New Game");
        newGameButton.setToolTipText("Start a new game.");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        changeBetButton.setText("Change Bet");
        changeBetButton.setToolTipText("Input the new amount of bet.");
        changeBetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBetButtonActionPerformed(evt);
            }
        });

        drawButton.setText("Draw");
        drawButton.setToolTipText("Draw one more card.");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        stayButton.setText("Stay");
        stayButton.setToolTipText("Don't draw any more card.");
        stayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayButtonActionPerformed(evt);
            }
        });

        currentFundLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        currentFundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentFundLabel.setText("Current Funds");

        betLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        betLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        betLabel.setText("Current Bet");
        betLabel.setToolTipText("The bet you have placed for this round.");

        betLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        betLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        betLabel2.setText("10");
        betLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fundLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fundLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundLabel2.setText("100");

        continueButton.setText("Continue");
        continueButton.setToolTipText("No game in progress.");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(currentFundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                        .addComponent(betLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59))
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(changeBetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(drawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(continueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(fundLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(betLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newGameButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(continueButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentFundLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fundLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(betLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(betLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(changeBetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drawButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stayButton)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {        
        Game.pc.drawMore();        
        cardPanel3.setVisible(true);
        jLabel3.setVisible(true);
        jLabel3.setText(Deck.getCard(Game.pc.card[2]));
        if (Game.pc.card[2] % 4 == 1 || Game.pc.card[2] % 4 == 2) {
            jLabel3.setForeground(Color.RED); //for Hearts and Diamonds
        } else {
            jLabel3.setForeground(Color.BLACK); //for Spades and Clubs
        }
        pointsLabel3.setText("" + Game.pc.getPoints()); //calculate new points
        drawButton.setEnabled(false);
        drawButton.setToolTipText("You can only draw once.");
        stayButton.setEnabled(false); //Automatically stay
        if (Game.pc.pokStat == true || Game.pc.dengStat > 1) {
            pokdengLabel1.setVisible(true);
            pokdengLabel1.setText(Game.pc.pok + " " + Game.pc.deng);
        }
        if (Game.dealer.getPoints() < 5) { //dealer draw after player draw, but only if dealer has fewer than 5 points
            Game.dealer.drawMore();
            pointsLabel4.setText("" + Game.dealer.getPoints());
        }
        showDealerCard();
        determineWinner();
    }

    private void changeBetButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int bet = 0;
        while (bet < 1) {
            try {
                bet = Integer.parseInt(JOptionPane.showInputDialog("Place your bet for this round."));
                if (bet < 1) {
                    JOptionPane.showMessageDialog(this, "Your bet must be greater than 0!", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (bet > Game.pc.getFund()) {
                    JOptionPane.showMessageDialog(this, "You can't bet more than you have!", "Error", JOptionPane.ERROR_MESSAGE);
                    bet = 0;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid input. Integer only!", "Error", JOptionPane.ERROR_MESSAGE);
                bet = 0;
            }
        }
        betLabel2.setText(Integer.toString(bet));
        Game.bet = bet;
    }

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {
        hideDealerCard();        
        changeBetButton.setEnabled(true);
        gameLabel1.setVisible(false);
        gameLabel2.setVisible(false);
        g.startNewGame();
        fundLabel2.setText("" + Game.pc.getFund());        
        fundLabel2.setForeground(Color.BLACK);
        drawButton.setEnabled(true);
        drawButton.setToolTipText("Draw one more card.");
        stayButton.setEnabled(true);
        showPCCard();
        if (Game.pc.pokStat == true || Game.pc.dengStat > 1) {
            pokdengLabel1.setVisible(true);
            pokdengLabel1.setText(Game.pc.pok + " " + Game.pc.deng);
        }
        pointsLabel4.setText("" + Game.dealer.getPoints());
        if (Game.dealer.pokStat == true) {
            dealerPok();
        }
        if (Game.pc.pokStat == true) {
            pcPok();
        }
    }

    private void stayButtonActionPerformed(java.awt.event.ActionEvent evt) {
        drawButton.setEnabled(false);
        drawButton.setToolTipText("You can't draw after you decided to stay!");
        stayButton.setEnabled(false);
        if (Game.dealer.getPoints() < 5) { //dealer draw after player stay
            Game.dealer.drawMore();
            pointsLabel4.setText("" + Game.dealer.getPoints());
        }
        showDealerCard();
        determineWinner();
    }

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {
        continueButton.setEnabled(false);
        pokdengLabel1.setVisible(false);
        g.startNewRound();
        hideDealerCard();
        gameLabel1.setVisible(false);
        gameLabel2.setVisible(false);
        changeBetButton.setEnabled(false);
        changeBetButton.setToolTipText("Can't change bet after round start.");
        drawButton.setEnabled(true);
        drawButton.setToolTipText("Draw one more card.");
        stayButton.setEnabled(true);
        pointsLabel4.setText("" + Game.dealer.getPoints());
        showPCCard();
        if (Game.dealer.pokStat == true) {
            dealerPok();
        }
        if (Game.pc.pokStat == true) {
            pcPok();
        }
    }

    public void showPCCard() {
        cardLabel1.setVisible(true);
        pointsLabel1.setVisible(true);
        pointsLabel3.setVisible(true);
        pointsLabel3.setText("" + Game.pc.getPoints());
        cardPanel1.setVisible(true);
        cardPanel2.setVisible(true);
        jLabel1.setVisible(true);
        jLabel1.setText(Deck.getCard(Game.pc.card[0]));
        if (Game.pc.card[0] % 4 == 1 || Game.pc.card[0] % 4 == 2) {
            jLabel1.setForeground(Color.RED); //Hearts, Diamonds
        } else {
            jLabel1.setForeground(Color.BLACK); //Spades, Clubs
        }
        jLabel2.setVisible(true);
        jLabel2.setText(Deck.getCard(Game.pc.card[1]));
        if (Game.pc.card[1] % 4 == 1 || Game.pc.card[1] % 4 == 2) {
            jLabel2.setForeground(Color.RED); //Hearts, Diamonds
        } else {
            jLabel2.setForeground(Color.BLACK); //Spades, Clubs
        }
        if (Game.pc.pokStat == true || Game.pc.dengStat > 1) {
            pokdengLabel1.setText(Game.pc.pok + " " + Game.pc.deng); //In case Pok or Deng
            pokdengLabel1.setVisible(true);
        }
    }

    public void hideDealerCard() {
        pokdengLabel2.setVisible(false);
        jLabel3.setVisible(false);
        cardPanel3.setVisible(false);
        cardLabel2.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        pointsLabel2.setVisible(false);
        pointsLabel4.setVisible(false);
        cardPanel4.setVisible(false);
        cardPanel5.setVisible(false);
        cardPanel6.setVisible(false);
    }

    public void showDealerCard() {
        cardLabel2.setVisible(true);
        pointsLabel2.setVisible(true);
        cardPanel4.setVisible(true);
        cardPanel5.setVisible(true);
        jLabel4.setVisible(true);
        jLabel4.setText(Deck.getCard(Game.dealer.card[0]));
        if (Game.dealer.card[0] % 4 == 1 || Game.dealer.card[0] % 4 == 2) {
            jLabel4.setForeground(Color.RED);
        } else {
            jLabel4.setForeground(Color.BLACK);
        }
        jLabel5.setVisible(true);
        jLabel5.setText(Deck.getCard(Game.dealer.card[1]));
        if (Game.dealer.card[1] % 4 == 1 || Game.dealer.card[1] % 4 == 2) {
            jLabel5.setForeground(Color.RED);
        } else {
            jLabel5.setForeground(Color.BLACK);
        }
        if (Game.dealer.drawmore == true) { //If dealer drawed, show one more card
            cardPanel6.setVisible(true);
            jLabel6.setVisible(true);
            jLabel6.setText(Deck.getCard(Game.dealer.card[2]));
            if (Game.dealer.card[2] % 4 == 1 || Game.dealer.card[2] % 4 == 2) {
                jLabel6.setForeground(Color.RED);
            } else {
                jLabel6.setForeground(Color.BLACK);
            }
        }
        if (Game.dealer.pokStat == true || Game.dealer.dengStat > 1) {
            pokdengLabel2.setVisible(true);
            pokdengLabel2.setText(Game.dealer.pok + " " + Game.dealer.deng);
        }
        pointsLabel2.setVisible(true);
        pointsLabel4.setVisible(true);
    }

    public void dealerPok() {
        showDealerCard();
        drawButton.setEnabled(false);
        drawButton.setToolTipText("Can't draw if dealer Pok.");
        stayButton.setEnabled(false);
        determineWinner();
    }

    public void pcPok() {
        showDealerCard();
        drawButton.setEnabled(false);
        drawButton.setToolTipText("Can't draw, already Pok.");
        stayButton.setEnabled(false);
        determineWinner();
    }

    public void determineWinner() { //the method finds out who wins based on the game's rules
        continueButton.setEnabled(true);
        continueButton.setToolTipText("Continue current game.");
        changeBetButton.setEnabled(true);
        gameLabel2.setText("Press continue or start a new game.");
        if (((Game.pc.getPoints() > Game.dealer.getPoints()) && Game.dealer.specialwin == false) || (Game.pc.specialwin == true && Game.dealer.specialwin == false)) {
            gameLabel1.setText("You win!");
            Game.pc.setFund(Game.bet * Game.pc.dengStat);
        } else if ((Game.pc.getPoints() == Game.dealer.getPoints()) || (Game.pc.specialwin == true && Game.dealer.specialwin == true)) {
            gameLabel1.setText("Tie!");
        } else if (((Game.pc.getPoints() < Game.dealer.getPoints()) && Game.pc.specialwin == false) || (Game.pc.specialwin == false && Game.dealer.specialwin == true)) {
            gameLabel1.setText("You lose!");
            Game.pc.setFund(-(Game.bet * Game.dealer.dengStat));
        }
        if (Game.pc.getFund() < 1) { //PC ran out of fund            
            changeBetButton.setEnabled(false);
            fundLabel2.setForeground(Color.RED);
            gameLabel1.setText("GAME OVER!");
            gameLabel2.setText("Start a new game to try again.");
            continueButton.setEnabled(false);
            continueButton.setToolTipText("The game is already over.");
        }
        if (Game.bet > Game.pc.getFund()) {
            Game.bet = Game.pc.getFund(); //can only bet what you have
            betLabel2.setText("" + Game.bet); //update new bet
        }
        gameLabel1.setVisible(true);
        gameLabel2.setVisible(true);
        changeBetButton.setToolTipText("Input the new amount of bet.");
        fundLabel2.setText("" + Game.pc.getFund()); //update funds
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokDeng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokDeng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokDeng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokDeng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PokDeng form = new PokDeng();
                form.setEnabled(true);
                form.setVisible(true);
                cardLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                pointsLabel1.setVisible(false);
                pointsLabel3.setVisible(false);
                cardPanel1.setVisible(false);
                cardPanel2.setVisible(false);
                cardPanel3.setVisible(false);
                cardLabel1.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                pointsLabel2.setVisible(false);
                pointsLabel4.setVisible(false);
                cardPanel4.setVisible(false);
                cardPanel5.setVisible(false);
                cardPanel6.setVisible(false);
                pokdengLabel1.setVisible(false);
                pokdengLabel2.setVisible(false);
                drawButton.setEnabled(false);
                stayButton.setEnabled(false);
                continueButton.setEnabled(false);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel betLabel;
    private javax.swing.JLabel betLabel2;
    protected static javax.swing.JLabel cardLabel1;
    protected static javax.swing.JLabel cardLabel2;
    protected static javax.swing.JPanel cardPanel1;
    protected static javax.swing.JPanel cardPanel2;
    protected static javax.swing.JPanel cardPanel3;
    protected static javax.swing.JPanel cardPanel4;
    protected static javax.swing.JPanel cardPanel5;
    protected static javax.swing.JPanel cardPanel6;
    private javax.swing.JButton changeBetButton;
    private static javax.swing.JButton continueButton;
    private javax.swing.JLabel currentFundLabel;
    protected static javax.swing.JButton drawButton;
    private javax.swing.JLabel fundLabel2;
    private static javax.swing.JLabel gameLabel1;
    private static javax.swing.JLabel gameLabel2;
    private java.awt.Panel gamePanel;
    protected static javax.swing.JLabel jLabel1;
    protected static javax.swing.JLabel jLabel2;
    protected static javax.swing.JLabel jLabel3;
    protected static javax.swing.JLabel jLabel4;
    protected static javax.swing.JLabel jLabel5;
    protected static javax.swing.JLabel jLabel6;
    private java.awt.Panel menuPanel;
    private javax.swing.JButton newGameButton;
    protected static javax.swing.JLabel pointsLabel1;
    protected static javax.swing.JLabel pointsLabel2;
    private static javax.swing.JLabel pointsLabel3;
    private static javax.swing.JLabel pointsLabel4;
    private static javax.swing.JLabel pokdengLabel1;
    private static javax.swing.JLabel pokdengLabel2;
    protected static javax.swing.JButton stayButton;
    // End of variables declaration                   
}
